ALTER TABLE BM_BOYING_GRUPPER ADD CONSTRAINT BM_PK_BOYING_GRUPPER PRIMARY KEY (BOY_GRUPPE);

ALTER TABLE BM_BOYING ADD CONSTRAINT BM_PK_BOYING PRIMARY KEY (BOY_NUMMER, BOY_GRUPPE);
ALTER TABLE BM_BOYING ADD CONSTRAINT BM_FK_BOYING_BOYING_GRUPPER FOREIGN KEY (BOY_GRUPPE) REFERENCES BM_BOYING_GRUPPER (BOY_GRUPPE);

ALTER TABLE BM_PARADIGME ADD CONSTRAINT BM_PK_PARADIRME PRIMARY KEY (PARADIGME_ID);
ALTER TABLE BM_PARADIGME ADD CONSTRAINT BM_FK_PARADIGME_BOY_GRUPPE FOREIGN KEY (BOY_GRUPPE) REFERENCES BM_BOYING_GRUPPER (BOY_GRUPPE);

ALTER TABLE BM_PARADIGME_BOYING ADD CONSTRAINT BM_PK_PARADIGME_BOYING PRIMARY KEY (PARADIGME_ID, BOY_NUMMER, BOY_GRUPPE);
ALTER TABLE BM_PARADIGME_BOYING ADD CONSTRAINT BM_FK_PARADIGME_BOYING_PARADIGME FOREIGN KEY (PARADIGME_ID) REFERENCES BM_PARADIGME (PARADIGME_ID);
ALTER TABLE BM_PARADIGME_BOYING ADD CONSTRAINT BM_FK_PARADIGME_BOYING_BOYING FOREIGN KEY (BOY_NUMMER, BOY_GRUPPE) REFERENCES BM_BOYING (BOY_NUMMER, BOY_GRUPPE);

ALTER TABLE BM_LEMMA ADD CONSTRAINT BM_PK_LEMMA PRIMARY KEY LEMMA (LEMMA_ID);

ALTER TABLE BM_LEMMA_PARADIGME ADD CONSTRAINT BM_PK_LEMMA_PARADIGME PRIMARY KEY (LEMMA_ID, PARADIGME_ID);
    DELETE FROM BM_LEMMA_PARADIGME WHERE LEMMA_ID = 159286; -- PATCH
ALTER TABLE BM_LEMMA_PARADIGME ADD CONSTRAINT BM_FK_LEMMA_PARADIGME_LEMMA FOREIGN KEY (LEMMA_ID) REFERENCES BM_LEMMA (LEMMA_ID);
ALTER TABLE BM_LEMMA_PARADIGME ADD CONSTRAINT BM_FK_LEMMA_PARADIGME_PARADIGME FOREIGN KEY (PARADIGME_ID) REFERENCES BM_PARADIGME (PARADIGME_ID);

ALTER TABLE BM_FULLFORMSLISTE ADD CONSTRAINT BM_PK_FULLFORMSLISTE PRIMARY KEY (LEMMA_ID, OPPSLAG, TAG, PARADIGME_ID, BOY_NUMMER);
    DELETE FROM BM_FULLFORMSLISTE WHERE LEMMA_ID NOT IN (SELECT LEMMA_ID FROM BM_LEMMA); -- PATCH
ALTER TABLE BM_FULLFORMSLISTE ADD CONSTRAINT BM_FK_FULLFORMSLISTE_LEMMA FOREIGN KEY (LEMMA_ID) REFERENCES BM_LEMMA (LEMMA_ID);

ALTER TABLE BM_LEDDANALYSE ADD CONSTRAINT BM_PK_LEDDANALYSE PRIMARY KEY (LEDDANALYSE_ID);
ALTER TABLE BM_LEDDANALYSE ADD CONSTRAINT BM_FK_LEDDANALYSE_LEMMA FOREIGN KEY (LEMMA_ID) REFERENCES BM_LEMMA (LEMMA_ID);
