DROP TABLE IF EXISTS NN_LEDDANALYSE;

DROP TABLE IF EXISTS NN_FULLFORMSLISTE;

DROP TABLE IF EXISTS NN_LEMMA_PARADIGME;

DROP TABLE IF EXISTS NN_LEMMA;

DROP TABLE IF EXISTS NN_PARADIGME_BOYING;

DROP TABLE IF EXISTS NN_PARADIGME;

DROP TABLE IF EXISTS NN_BOYING;

DROP TABLE IF EXISTS NN_BOYING_GRUPPER;
