DROP TABLE IF EXISTS BM_LEDDANALYSE;

DROP TABLE IF EXISTS BM_FULLFORMSLISTE;

DROP TABLE IF EXISTS BM_LEMMA_PARADIGME;

DROP TABLE IF EXISTS BM_LEMMA;

DROP TABLE IF EXISTS BM_PARADIGME_BOYING;

DROP TABLE IF EXISTS BM_PARADIGME;

DROP TABLE IF EXISTS BM_BOYING;

DROP TABLE IF EXISTS BM_BOYING_GRUPPER;
