DROP TABLE IF EXISTS LEDDANALYSE;

DROP TABLE IF EXISTS FULLFORMSLISTE;

DROP TABLE IF EXISTS LEMMA_PARADIGME;

DROP TABLE IF EXISTS LEMMA;

DROP TABLE IF EXISTS PARADIGME_BOYING;

DROP TABLE IF EXISTS PARADIGME;

DROP TABLE IF EXISTS BOYING;

DROP TABLE IF EXISTS BOYING_GRUPPER;
